### ISSUE TITLE
Bug: mismatch user 

### ISSUE THREAD

**Issue by IngridMoen** [Uninett/Argus-frontend#321] opened 2021-08-23 13:38 UTC
**Describe the bug**
Logged in with my Feide user (Ingrid Moen), but once logged in, the username in the upper right corner is "Gjermund". Could not change user once logged in on Argus.

**To Reproduce**
1. Go to argus.uninett.no
2. Log in with username and password with feide
3. See error - mismatch between logged on user and user name

**Expected behavior**
I expected to log in om my own user, and not on to someone elses, when I use my username and password.

**Screenshots**
![Skjermbilde 2021-08-23 153642](https://user-images.githubusercontent.com/89390195/130456786-9fc34416-c9fa-4d39-a300-a706873ab65f.png)

![Skjermbilde 2021-08-23 130356](https://user-images.githubusercontent.com/89390195/130457041-591b5d63-a9fb-407c-835b-e9b131d35402.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge
 
**Additional context**
Tried to log out and start over with new log in, but nothing changed.

**Comment by hmpf** [comment] 2021-11-26 07:07
I suspect this might be solved by #341.

**Comment by lunkwill42** [comment] 2021-12-02 10:57
@IngridMoen  Thanks for the bug report. #341 has been pushed to Uninett production now. Are you be able to verify whether this resolves your issue?

**Comment by podliashanyk** [comment] 2022-06-09 09:36
I can confirm that issue is fixed for user-password login. It should also be fixed for Feide login as well, as there are no  differences related to frontend components between those two login methods. But to be sure it should also be checked for Feide login specifically.

**Comment by podliashanyk** [comment] 2022-10-05 12:45
**UPD:** @IngridMoen, the bug is reproduced.

#### Desktop:
OS: macOS Monterey 12.6
Browsers: Firefox 105.0, Safari 16.0

#### Comment from the Feide team:
The bug belongs to the Feide system itself. Feide team doesn't prioritise the bugfix, since they have identified that 2 users using Feide-login in the same browser is a seldom scenario. 
Their recommendation is to either use 2 different browsers, or to clear the browser caches between login-sessions. 


I am closing this issue, since the fix is unattainable within Argus.

**Closed** 2022-10-05 12:54 UTC
Labels: bug, priority: high
