### ISSUE TITLE
Bug: selection of multiple incidents is not "cleared" when action is preformed 

### ISSUE THREAD

**Issue by vidarstokke** [Uninett/Argus-frontend#284] opened 2021-07-01 09:01 UTC
**Describe the bug**
When I select multiple incidents and perform an action on them, ie. ack them, then they are still selected afterwards. 

**To Reproduce**
1. Go to main Argus page
2. Select multiple incidents
3. Push ACK to ack these incidents. 
4. After ACK is performed, the incidents are still selected. 

**Expected behavior**
After performing an action on multiple incidents, the selection should be cleared. Otherwise I end up acking these incidents as well when I do a new selection of multiple incidents. 

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Chrome

**Comment by podliashanyk** [comment] 2021-07-01 10:29
This issue should now be fixed by PR #275

**Comment by lunkwill42** [comment] 2021-07-26 07:57
Potentially a duplicate of #242

**Closed by lunkwill42** 2021-07-26 07:57 UTC
Labels: bug
